version: 2.1

orbs:
  architect: giantswarm/architect@5.3.1

workflows:
  build:
    jobs:
      - architect/go-test:
          name: go-test
          # Needed to trigger job also on git tag.
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
