name: Verify values.schema.json
description: Verfies values.schema.json with schemalint verify and the specified rule set
inputs:
  rule-set:
    description: Rule set to use for verify command
runs:
  using: composite
  steps:
    - name: Install schemalint
      uses: giantswarm/install-binary-action@4b9f8dcb6b036f2d4c570718ee5417ecc2cb4d67 # v3.1.0
      with:
        binary: "schemalint"
        version: "2.6.1"
    - name: Run schemalint
      shell: bash
      run: ${{ github.action_path }}/verify-helm-schema.sh ${{ inputs.rule-set }}
