name: Verify values.schema.json
description: Verfies values.schema.json with schemalint verify and the specified rule set
inputs:
  rule-set:
    description: Rule set to use for verify command
runs:
  using: composite
  steps:
    - name: Install schemalint
      uses: giantswarm/install-binary-action@c94c7adadeb14af4bdbdd601f9a6e7f69638134c # v4.0.0
      with:
        binary: "schemalint"
        version: "2.6.1"
    - name: Run schemalint
      shell: bash
      run: ${{ github.action_path }}/verify-helm-schema.sh ${{ inputs.rule-set }}
