name: Verify values.schema.json
description: Verfies values.schema.json with schemalint verify and the specified rule set
inputs:
  rule-set:
    description: Rule set to use for verify command
runs: 
  using: composite
  steps:
    - id: get_version
      uses: battila7/get-version-action@v2
    - name: Install schemalint
      uses: giantswarm/install-binary-action@v1.1.0
      with:
        binary: "schemalint"
        version: ${{ steps.get_version.outputs.version-without-v }}

    - run: echo ${{ steps.get_version.outputs.version }}
      shell: bash
    - run: echo ${{ steps.get_version.outputs.version-without-v }}
      shell: bash

    - name: Run schemalint
      shell: bash
      run: ${{ github.action_path }}/verify-helm-schema.sh ${{ inputs.rule-set }}
